Bugfix: We need to use utf8mb4 as the MySQL charset for proper data storage
Resolves the following error:
pony.orm.core.UnexpectedError: Object TwitterBlocklist[1125605984510984192] cannot be stored in the database. DataError: 1366 Incorrect string value: '\xF0\x9F\x8E\xB8\xE2\x9C...' for column `twitter_saucebot`.`twitterblocklist`.`display_name` at row 1